# Generated by Django 5.0.2 on 2024-03-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
    ]
