# Generated by Django 5.0.2 on 2024-03-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
